server:
  port:
    8083
spring:
  nodeValue: jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/speakiv
    driverClassName: com.mysql.cj.jdbc.Driver
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/